name: BedWars
main: BedWars\Game
src-namespace-prefix: BedWars
version: 1.0.0
api: 4.0.0

commands:
  bedwars:
    description: "ยง7BedWars Setup Command"
    aliases:
      - bw
    permission: bedwars.setup
  start:
    description: "ยง6Starte die BedWars Runde!"
    aliases:
      - s
    permission: bedwars.start

permissions:
  bedwars.setup:
    description: "/bedwars"
    default: true
  bedwars.start:
    description: "/start"
    default: true